apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: hello-world
  type: LoadBalancer